#ifndef INC_BOOTLOADER_H
#define INC_BOOTLOADER_H
#include<libopencm3/stm32/memorymap.h>

#define BOOTLOADER_SIZE (0x4000U)
#define FIRMWARE_VECTOR_START (FLASH_BASE + BOOTLOADER_SIZE)
#define FIRMWARE_START_PAGE (16)
#define FIRMWARE_END_PAGE (24)
#define MAX_FIRMWARE_LENGTH ((1024 * 24) - BOOTLOADER_SIZE )

#endif // !INC_BOOTLOADER_H
